"use strict";
let x = 10;
let y = 5;
// console.log(x>y);
console.log("Is x > y? I predict True.");
console.log(x > y);
console.log("Is x < y? I predict False.");
console.log(x < y);
console.log("Is x == y? I predict False.");
console.log(x == y);
console.log("Is x != y? I predict True.");
console.log(x != y);
console.log("Is x >= y? I predict True.");
console.log(x >= y);
console.log("Is y >= x? I predict False.");
console.log(y >= x);
console.log("Is x <= y? I predict False.");
console.log(x <= y);
console.log("Is y <= x? I predict True.");
console.log(y <= x);
console.log("Is x > 5 and x < 15? I predict True.");
console.log(x > 5 && x < 15);
console.log("Is y > 10 or y < 3? I predict False.");
console.log(y > 10 || y < 3);
